trajets_tests:
    path:     /tests
    defaults: { _controller: TrajetsBundle:Test:index }

trajets_homepage:
    path:     /
    defaults: { _controller: TrajetsBundle:Carte:affichage }

trajets_admin:
    path:     /admin
    defaults: { _controller: TrajetsBundle:Admin:index }

trajets_lieux:
    resource: "@TrajetsBundle/Resources/config/routing/lieu.yml"
    prefix:   /lieux