# app/config/security.yml

security:
  encoders:
    Symfony\Component\Security\Core\User\User: plaintext

  role_hierarchy:
    ROLE_COLLECTEUR:       ROLE_USER
    ROLE_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

  providers:
    in_memory:
      memory:
        users:
          collecteur:  { password: userpass, roles: [ 'ROLE_COLLECTEUR' ] }
          admin@admin.fr: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main_login:
      pattern: ^/login$
      anonymous: true
    main:
      pattern:   ^/
      anonymous: false
      form_login:
        login_path: trajets_login
        check_path: trajets_login_check
      logout:
        path: trajets_logout
        target: /login

  access_control:
    #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
